Repository italia/designers.italia.it, pull requests merged in 2022-10, with the labels that each got.

#223 Kit privacy policy abilitato per preview
  _kits/it/privacy.md
  _layouts/kit.html
  assets/icons/kit/kit_privacy_basi.svg
Labels: feature, content

#384 Added new accordions
  _modelli/it/comuni.md
  _modelli/it/scuole.md
Labels: enhancement

#385 feat/update piano attivita
  _data/attivita.yml
Labels: content

#386 Web analytics update
  _kits/it/web-analytics.md
Labels: content

#390 Next/Update README.md
  README.md
Labels: next
