Repository italia/designers.italia.it, pull requests merged in 2022-11, with the labels that each got.

#416 Update attivita.yml - new UI kit released
  _data/attivita.yml
Labels: content

#417 feat/kit progettazione interfaccia - nuovo UI kit
  _kits/it/progettazione-interfaccia.md
  _kits/it/sviluppo-interfaccia.md
Labels: content

#437 Feat/next content templates
  src/components/highlight/highlight.js
  src/components/highlight/highlight.scss
  src/pages/community.js
  src/pages/community.yaml
  src/pages/level1.yaml
  src/pages/level1/level2.yaml
  src/pages/level1/level2/level3.yaml
  src/pages/progetto.js
  src/pages/progetto.yaml
  src/pages/progetto/visione-e-missione.js
  src/pages/progetto/visione-e-missione.yaml
  src/pages/test-components/highlight.yaml
Labels: content, next

#443 Feat/next menu fixes and contents
  src/components/header-menu-link/header-menu-link.js
  src/components/megamenu/megamenu.js
  src/components/megamenu/megamenu.scss
  src/data/header.yaml
  src/data/skiplinks.yaml
  src/pages/community.js
  src/pages/community.yaml
Labels: next, done - to be verified

#459 feat/next-content-menu
  src/data/header.yaml
Labels: content, next

#467 Fix/feedback title a11y
  src/components/feedback/components/form-no/FormNo.js
Labels: bug, next, a11y

#471 Feat/next banner prossima
  src/components/header-pre/header-pre.js
  src/data/header.yaml
  src/templates/tmpl-base.js
  src/templates/tmpl-design-system-index.js
  src/templates/tmpl-level-1-community.js
  src/templates/tmpl-level-1.js
  src/templates/tmpl-level-2.js
  src/templates/tmpl-level-3.js
  src/templates/tmpl-level-4.js
Labels: feature, next

#476 Feat/next announce slim banner post header + various fixes (menu + class in svgs)
  src/components/header-menu-link/header-menu-link.js
  src/components/header-post/header-post.js
  src/components/header-pre/header-pre.js
  src/data/header.yaml
  src/templates/tmpl-base.js
  static/images/conversation.svg
  static/images/designers-italia-logo-footer.svg
Labels: feature, next, done - to be verified

#475 Feat/next design system detail
  src/components/card/card.scss
  src/components/chip/chip.scss
  src/components/dropdown/dropdown.js
  src/components/header-nav/header-nav.js
  src/components/section-editorial/section-editorial.js
  src/components/table/table.js
  src/components/table/table.scss
  src/data/header.yaml
  src/pages/community.yaml
  src/pages/index.js
  src/pages/level1/componenti/componente.js
  src/pages/level1/componenti/componente.yaml
  src/pages/level1/fondamenti.yaml
  src/pages/level1/fondamenti/fondamento.js
  src/pages/level1/fondamenti/fondamento.yaml
  src/pages/level1/level2.yaml
Labels: feature, next

#478 Feat/component feedback rev2
  src/components/feedback/feedback.js
Labels: enhancement, next

#480 fix: mouse focus script in build
  src/templates/tmpl-base.js
Labels: bug, next, a11y

#470 Feat/next-content-comprendere-gianvito
  src/pages/risorse-per-progettare/comprendere.yaml
  src/pages/risorse-per-progettare/comprendere/analisi-del-contesto.js
  src/pages/risorse-per-progettare/comprendere/analisi-del-contesto.yaml
  src/pages/risorse-per-progettare/comprendere/analisi-del-contesto/schematizza-il-contesto-d-uso-di-un-servizio.js
  src/pages/risorse-per-progettare/comprendere/analisi-del-contesto/schematizza-il-contesto-d-uso-di-un-servizio.yaml
  src/pages/risorse-per-progettare/comprendere/esperienza-utente.js
  src/pages/risorse-per-progettare/comprendere/esperienza-utente.yaml
  src/pages/risorse-per-progettare/comprendere/esperienza-utente/analizza-l-esperienza-d-uso.js
  src/pages/risorse-per-progettare/comprendere/esperienza-utente/analizza-l-esperienza-d-uso.yaml
  src/pages/risorse-per-progettare/comprendere/esperienza-utente/definisci-le-personas.js
  src/pages/risorse-per-progettare/comprendere/esperienza-utente/definisci-le-personas.yaml
  src/pages/risorse-per-progettare/comprendere/interviste-soggetti-coinvolti.js
  src/pages/risorse-per-progettare/comprendere/interviste-soggetti-coinvolti.yaml
  src/pages/risorse-per-progettare/comprendere/interviste-soggetti-coinvolti/pianifica-le-interviste.js
  src/pages/risorse-per-progettare/comprendere/interviste-soggetti-coinvolti/pianifica-le-interviste.yaml
  src/pages/risorse-per-progettare/comprendere/interviste-soggetti-coinvolti/predisponi-il-protocollo.js
  src/pages/risorse-per-progettare/comprendere/interviste-soggetti-coinvolti/predisponi-il-protocollo.yaml
  src/pages/risorse-per-progettare/comprendere/interviste-soggetti-coinvolti/rielabora-le-informazioni.js
  src/pages/risorse-per-progettare/comprendere/interviste-soggetti-coinvolti/rielabora-le-informazioni.yaml
  src/pages/risorse-per-progettare/comprendere/level3.yaml
  src/pages/risorse-per-progettare/comprendere/level3/level4.yaml
  src/pages/risorse-per-progettare/comprendere/questionario-online.js
  src/pages/risorse-per-progettare/comprendere/questionario-online.yaml
  src/pages/risorse-per-progettare/comprendere/questionario-online/pianifica-l-indagine.js
  src/pages/risorse-per-progettare/comprendere/questionario-online/pianifica-l-indagine.yaml
  src/pages/risorse-per-progettare/comprendere/questionario-online/sintetizza-i-risultati-della-ricerca.js
  src/pages/risorse-per-progettare/comprendere/questionario-online/sintetizza-i-risultati-della-ricerca.yaml
Labels: content, next

#455 Feat/next content comprendere
  src/pages/risorse-per-progettare/comprendere.js
  src/pages/risorse-per-progettare/comprendere.yaml
  src/pages/risorse-per-progettare/comprendere/analisi-del-contesto.js
  src/pages/risorse-per-progettare/comprendere/analisi-del-contesto.yaml
  src/pages/risorse-per-progettare/comprendere/analisi-del-contesto/schematizza-il-contesto-d-uso-di-un-servizio.js
  src/pages/risorse-per-progettare/comprendere/analisi-del-contesto/schematizza-il-contesto-d-uso-di-un-servizio.yaml
  src/pages/risorse-per-progettare/comprendere/esperienza-utente.js
  src/pages/risorse-per-progettare/comprendere/esperienza-utente.yaml
  src/pages/risorse-per-progettare/comprendere/esperienza-utente/analizza-l-esperienza-d-uso.js
  src/pages/risorse-per-progettare/comprendere/esperienza-utente/analizza-l-esperienza-d-uso.yaml
  src/pages/risorse-per-progettare/comprendere/esperienza-utente/definisci-le-personas.js
  src/pages/risorse-per-progettare/comprendere/esperienza-utente/definisci-le-personas.yaml
  src/pages/risorse-per-progettare/comprendere/interviste-soggetti-coinvolti.js
  src/pages/risorse-per-progettare/comprendere/interviste-soggetti-coinvolti.yaml
  src/pages/risorse-per-progettare/comprendere/interviste-soggetti-coinvolti/pianifica-le-interviste.js
  src/pages/risorse-per-progettare/comprendere/interviste-soggetti-coinvolti/pianifica-le-interviste.yaml
  src/pages/risorse-per-progettare/comprendere/interviste-soggetti-coinvolti/predisponi-il-protocollo.js
  src/pages/risorse-per-progettare/comprendere/interviste-soggetti-coinvolti/predisponi-il-protocollo.yaml
  src/pages/risorse-per-progettare/comprendere/interviste-soggetti-coinvolti/rielabora-le-informazioni.js
  src/pages/risorse-per-progettare/comprendere/interviste-soggetti-coinvolti/rielabora-le-informazioni.yaml
  src/pages/risorse-per-progettare/comprendere/questionario-online.js
  src/pages/risorse-per-progettare/comprendere/questionario-online.yaml
  src/pages/risorse-per-progettare/comprendere/questionario-online/pianifica-l-indagine.js
  src/pages/risorse-per-progettare/comprendere/questionario-online/pianifica-l-indagine.yaml
  src/pages/risorse-per-progettare/comprendere/questionario-online/sintetizza-i-risultati-della-ricerca.js
  src/pages/risorse-per-progettare/comprendere/questionario-online/sintetizza-i-risultati-della-ricerca.yaml
  src/pages/risorse-per-progettare/organizzare.js
  src/pages/risorse-per-progettare/organizzare.yaml
  src/pages/risorse-per-progettare/organizzare/privacy.js
  src/pages/risorse-per-progettare/organizzare/privacy.yaml
  src/pages/risorse-per-progettare/organizzare/privacy/level4.js
  src/pages/risorse-per-progettare/organizzare/privacy/level4.yaml
Labels: content, next
