Repository italia/designers.italia.it, pull requests merged in 2022-12, with the labels that each got.

#491 feat: gatsby link component
  src/components/button/button.js
  src/components/card/card.js
  src/components/chip/chip.js
  src/components/feedback/components/form-no/FormNo.js
  src/components/footer-brand/footer-brand.js
  src/components/footer-main/footer-main.js
  src/components/footer-small/footer-small.js
  src/components/header-center/header-center.js
  src/components/header-post/header-post.js
  src/components/header-pre/header-pre.js
  src/components/img-full/img-full.scss
  src/components/last-update/last-update.js
  src/components/link-custom/link-custom.js
  src/components/link/link.js
  src/components/list-item/list-item.js
  src/components/list/list.js
  src/components/megamenu/megamenu.js
  src/components/nav-position/nav-position.js
  src/components/simple-cta/simple-cta.js
  src/components/tag/tag.js
  src/data/footer.yaml
  src/data/header.yaml
Labels: bug, next, done - to be verified

#502 fix: header megamenu a11y
  src/components/header-menu-link/header-menu-link.js
  src/components/header-menu-link/header-menu-link.scss
  src/components/megamenu/megamenu.js
  src/components/megamenu/megamenu.scss
Labels: bug, next, a11y, done - to be verified

#454 Feat/next content organizzare
  src/pages/risorse-per-progettare/organizzare.yaml
  src/pages/risorse-per-progettare/organizzare/privacy.yaml
  src/pages/risorse-per-progettare/organizzare/privacy/rispetta-la-privacy-per-il-go-live-di-un-sito.js
  src/pages/risorse-per-progettare/organizzare/privacy/rispetta-la-privacy-per-il-go-live-di-un-sito.yaml
  src/pages/risorse-per-progettare/organizzare/privacy/rispetta-la-privacy-quando-coinvolgi-gli-utenti-nella-ricerca.js
  src/pages/risorse-per-progettare/organizzare/privacy/rispetta-la-privacy-quando-coinvolgi-gli-utenti-nella-ricerca.yaml
  src/pages/risorse-per-progettare/organizzare/privacy/rispetta-la-privacy-quando-usi-i-social-network.js
  src/pages/risorse-per-progettare/organizzare/privacy/rispetta-la-privacy-quando-usi-i-social-network.yaml
Labels: content, next

#450 feat/next-content-modelli
  src/pages/modelli.js
  src/pages/modelli.yaml
  src/pages/modelli/comuni.js
  src/pages/modelli/comuni.yaml
  src/pages/modelli/comuni/adotta-il-modello-di-servizi-digitali-comunali.js
  src/pages/modelli/comuni/adotta-il-modello-di-servizi-digitali-comunali.yaml
  src/pages/modelli/comuni/adotta-il-modello-di-servizi-digitali-comunali/comprendi-lo-stato-dell-arte.js
  src/pages/modelli/comuni/adotta-il-modello-di-servizi-digitali-comunali/comprendi-lo-stato-dell-arte.yaml
  src/pages/modelli/comuni/adotta-il-modello-di-servizi-digitali-comunali/progetta-il-flusso-di-servizio.js
  src/pages/modelli/comuni/adotta-il-modello-di-servizi-digitali-comunali/progetta-il-flusso-di-servizio.yaml
  src/pages/modelli/comuni/adotta-il-modello-di-servizi-digitali-comunali/realizza-l-interfaccia-del-servizio-digitale-comunale.js
  src/pages/modelli/comuni/adotta-il-modello-di-servizi-digitali-comunali/realizza-l-interfaccia-del-servizio-digitale-comunale.yaml
  src/pages/modelli/comuni/adotta-il-modello-di-sito-comunale.js
  src/pages/modelli/comuni/adotta-il-modello-di-sito-comunale.yaml
  src/pages/modelli/comuni/adotta-il-modello-di-sito-comunale/comprendi-lo-stato-dell-arte.js
  src/pages/modelli/comuni/adotta-il-modello-di-sito-comunale/comprendi-lo-stato-dell-arte.yaml
  src/pages/modelli/comuni/adotta-il-modello-di-sito-comunale/definisci-architettura-e-contenuti.js
  src/pages/modelli/comuni/adotta-il-modello-di-sito-comunale/definisci-architettura-e-contenuti.yaml
  src/pages/modelli/comuni/adotta-il-modello-di-sito-comunale/realizza-l-interfaccia-del-sito-comunale.js
  src/pages/modelli/comuni/adotta-il-modello-di-sito-comunale/realizza-l-interfaccia-del-sito-comunale.yaml
  src/pages/modelli/comuni/adotta-il-modello-di-sito-comunale/valuta-l-adesione-al-modello-di-sito-comunale.js
  src/pages/modelli/comuni/adotta-il-modello-di-sito-comunale/valuta-l-adesione-al-modello-di-sito-comunale.yaml
  src/pages/modelli/scuole.js
  src/pages/modelli/scuole.yaml
Labels: content, next

#501 feat/next-content-norme-e-riferimenti-gabriella
  src/pages/norme-e-riferimenti.yaml
  src/pages/norme-e-riferimenti/linee-guida-di-design.yaml
  src/pages/norme-e-riferimenti/manuale-operativo.yaml
Labels: content, next

#497 feat/next-content-norme-e-riferimenti
  src/pages/norme-e-riferimenti.js
  src/pages/norme-e-riferimenti.yaml
  src/pages/norme-e-riferimenti/linee-guida-di-design.js
  src/pages/norme-e-riferimenti/linee-guida-di-design.yaml
  src/pages/norme-e-riferimenti/manuale-operativo.js
  src/pages/norme-e-riferimenti/manuale-operativo.yaml
Labels: content, next

#490 Fix/next-content-fixes-various
  src/pages/progetto.yaml
  src/pages/risorse-per-progettare/comprendere.yaml
Labels: content, next

#519 feat/next-content-roadmap
  src/pages/community/piano-attivita.yaml
Labels: content, next

#534 Feat/hero component detail
  src/components/hero/hero.js
  src/pages/design-system/componenti/componente.yaml
Labels: enhancement

#538 Feat/content evolve norme e riferimenti
  src/pages/norme-e-riferimenti.js
  src/pages/norme-e-riferimenti.yaml
  src/pages/norme-e-riferimenti/linee-guida-di-design.js
  src/pages/norme-e-riferimenti/linee-guida-sull-accessibilita.js
  src/pages/norme-e-riferimenti/manuale-operativo-di-design.js
  static/images/community/articoli-di-approfondimento/2021-medium-zaia-processo.webp
  static/images/community/articoli-di-approfondimento/2022-medium-filippi-etica.webp
  static/images/community/articoli-di-approfondimento/2022-medium-tabellini-accessibilita.webp
Labels: enhancement, content, next

#536 Fix/a11y component viewer and more
  src/components/chip/chip.js
  src/components/component-view/component-view.js
  src/components/tab/tab.js
  src/pages/community.yaml
  src/pages/design-system/componenti/componente-01-uso.yaml
  src/pages/design-system/componenti/componente-03-sviluppo.yaml
Labels: bug, next, a11y, done - to be verified

#546 Fix/a11y wrap checkbox
  src/components/checkbox/checkbox.js
  src/components/component-view/component-view.js
Labels: bug, next, a11y

#547 feat: make the feedback UI use the backend
  src/components/feedback/components/form-no/FormNo.js
  src/components/feedback/components/form-yes/FormYes.js
  src/components/feedback/feedback.js
  src/components/feedback/state.js
Labels: feature, next

#548 feat/next-content-privacy-fix
  src/pages/risorse-per-progettare/organizzare/privacy.yaml
  src/pages/risorse-per-progettare/organizzare/privacy/rispetta-la-privacy-per-il-go-live-di-un-sito.yaml
  src/pages/risorse-per-progettare/organizzare/privacy/rispetta-la-privacy-quando-coinvolgi-gli-utenti-nella-ricerca.yaml
  src/pages/risorse-per-progettare/organizzare/privacy/rispetta-la-privacy-quando-usi-i-social-network.yaml
Labels: content, next

#549 feat/next-content-progettare-fase-kitSEO
  src/pages/risorse-per-progettare/progettare.yaml
  src/pages/risorse-per-progettare/progettare/seo.js
  src/pages/risorse-per-progettare/progettare/seo.yaml
  src/pages/risorse-per-progettare/progettare/seo/definisci-gli-interventi-seo.js
  src/pages/risorse-per-progettare/progettare/seo/definisci-gli-interventi-seo.yaml
  src/pages/risorse-per-progettare/progettare/seo/pianifica-le-attivita-di-ottimizzazione.js
  src/pages/risorse-per-progettare/progettare/seo/pianifica-le-attivita-di-ottimizzazione.yaml
Labels: content, next

#550 feat: add mailing list registration
  src/components/subscribe/subscribe.js
  src/data/footer.yaml
Labels: feature, next

#552 fix: workaround for textarea labels overlapping the content
  src/components/feedback/components/form-no/FormNo.js
  src/components/feedback/feedback.scss
  src/components/label-textarea/label-text-area.js
Labels: bug, next

#560 fix(a11y): sidebar button instead of a #524
  src/components/nav-sidebar/nav-sidebar.js
  src/components/nav-sidebar/nav-sidebar.scss
Labels: bug, next

#561 fix: level 1 active page style on menubar
  src/pages/community.yaml
  src/pages/design-system.yaml
  src/pages/modelli.yaml
  src/pages/norme-e-riferimenti.yaml
  src/pages/progetto.yaml
  src/pages/risorse-per-progettare.yaml
  src/templates/tmpl-level-1-community.js
  src/templates/tmpl-level-1.js
Labels: enhancement, feature, next

#559 feat: make share-on-social menu work
  src/components/list-item/list-item.js
  src/components/list/list.js
Labels: feature, next

#562 feat/next-content-design-system-page-fix
  src/pages/design-system.yaml
Labels: content, next

#558 feat/next-content-co-progettazione-kit
  src/pages/risorse-per-progettare/progettare/co-progettazione.js
  src/pages/risorse-per-progettare/progettare/co-progettazione.yaml
  src/pages/risorse-per-progettare/progettare/co-progettazione/co-progetta-i-contenuti.js
  src/pages/risorse-per-progettare/progettare/co-progettazione/co-progetta-i-contenuti.yaml
  src/pages/risorse-per-progettare/progettare/co-progettazione/co-progetta-l-esperienza-d-uso.js
  src/pages/risorse-per-progettare/progettare/co-progettazione/co-progetta-l-esperienza-d-uso.yaml
Labels: content, next

#569 fix/a11y header pre before skip links
  src/components/header-pre/header-pre.js
  src/templates/tmpl-base.js
  src/templates/tmpl-design-system-detail.js
  src/templates/tmpl-design-system-index.js
  src/templates/tmpl-home.js
  src/templates/tmpl-level-1-community.js
  src/templates/tmpl-level-1.js
  src/templates/tmpl-level-2.js
  src/templates/tmpl-level-3.js
  src/templates/tmpl-level-4.js
Labels: a11y

#570 Fix/a11y header post dedicated section
  src/components/header-post/header-post.js
  src/templates/tmpl-base.js
  src/templates/tmpl-design-system-detail.js
  src/templates/tmpl-design-system-index.js
  src/templates/tmpl-home.js
  src/templates/tmpl-level-1-community.js
Labels: next, a11y

#565 fix(a11y): sidebar nav outside of main
  src/templates/tmpl-design-system-detail.js
  src/templates/tmpl-design-system-index.js
Labels: enhancement, next, a11y

#563 fix(a11y): don't stuff content into h2 in feedback UI
  src/components/feedback/feedback.js
Labels: bug, next, a11y

#568 feat/modelli-open-files
  static/files/resources/modelli/comuni/adotta-il-modello-di-servizi-digitali-comunali/comprendi-lo-stato-dell-arte/Strumento-checklist-servizi-comuni.odt
  static/files/resources/modelli/comuni/adotta-il-modello-di-servizi-digitali-comunali/comprendi-lo-stato-dell-arte/Tipologie-flussi-di servizio.ods
  static/files/resources/modelli/comuni/adotta-il-modello-di-sito-comunale/comprendi-lo-stato-dell-arte/Strumento-checklist-sito-comuni.odt
  static/files/resources/modelli/comuni/adotta-il-modello-di-sito-comunale/definisci-architettura-e-contenuti/Architettura-informazione-sito-Comuni.ods
  static/files/resources/modelli/scuole/adotta-il-modello-di-sito-scolastico/comprendi-lo-stato-dell-arte/Strumento-checklist-sito-scuole.odt
  static/files/resources/modelli/scuole/adotta-il-modello-di-sito-scolastico/definisci-architettura-e-contenuti/Architettura-informazione-sito-scuole.ods
Labels: content, next

#573 feat/urlHidden a11y for resources
  src/components/list-item/list-item.js
  src/pages/community/piano-attivita.yaml
  src/pages/level1/level2.yaml
  src/pages/level1/level2/article-detail.yaml
  src/pages/level1/level2/level3.yaml
  src/pages/level1/level2/level3/level4.yaml
  src/pages/modelli/comuni.yaml
  src/pages/modelli/comuni/adotta-il-modello-di-servizi-digitali-comunali.yaml
  src/pages/modelli/comuni/adotta-il-modello-di-sito-comunale.yaml
  src/pages/modelli/scuole.yaml
  src/pages/modelli/scuole/adotta-il-modello-di-sito-scolastico.yaml
  src/pages/norme-e-riferimenti/linee-guida-accessibilita.yaml
  src/pages/norme-e-riferimenti/linee-guida-di-design.yaml
  src/pages/norme-e-riferimenti/linee-guida-di-design/requisito-4-3.yaml
  src/pages/norme-e-riferimenti/linee-guida-di-design/requisito-4-3/azione-b.yaml
  src/pages/norme-e-riferimenti/manuale-operativo-di-design.yaml
  src/pages/progetto/storia.yaml
  src/pages/risorse-per-progettare/comprendere/analisi-del-contesto.yaml
  src/pages/risorse-per-progettare/comprendere/esperienza-utente.yaml
  src/pages/risorse-per-progettare/comprendere/interviste-soggetti-coinvolti.yaml
  src/pages/risorse-per-progettare/comprendere/questionario-online.yaml
  src/pages/risorse-per-progettare/organizzare/privacy.yaml
  src/pages/risorse-per-progettare/progettare/architettura-dell-informazione.yaml
  src/pages/risorse-per-progettare/progettare/co-progettazione.yaml
  src/pages/risorse-per-progettare/progettare/contenuti-e-linguaggio.yaml
  src/pages/risorse-per-progettare/progettare/prototipazione.yaml
  src/pages/risorse-per-progettare/progettare/seo.yaml
  src/pages/risorse-per-progettare/realizzare/costruzione-interfaccia.yaml
  src/pages/risorse-per-progettare/realizzare/sviluppo-interfaccia.yaml
  src/pages/risorse-per-progettare/validare/test-di-usabilita.yaml
  src/pages/risorse-per-progettare/validare/web-analytics.yaml
  src/pages/test-components/section-editorial.yaml
  src/pages/test-components/text-image-cta.yaml
Labels: bug, feature, next, a11y

#574 Feat/next ds components
  src/data/dsnav.yaml
  src/pages/design-system/componenti/buttons-01-uso.yaml
  src/pages/design-system/componenti/buttons-02-progettazione.yaml
  src/pages/design-system/componenti/buttons-03-sviluppo.yaml
  src/pages/design-system/componenti/buttons.js
  src/pages/design-system/componenti/buttons.json
  src/pages/design-system/componenti/buttons.yaml
  src/pages/design-system/componenti/dropdown-01-uso.yaml
  src/pages/design-system/componenti/dropdown-02-progettazione.yaml
  src/pages/design-system/componenti/dropdown-03-sviluppo.yaml
  src/pages/design-system/componenti/dropdown.js
  src/pages/design-system/componenti/dropdown.json
  src/pages/design-system/componenti/dropdown.yaml
Labels: feature, content, next

#567 fix: nav wrapper
  gatsby-browser.js
  src/components/checkbox/checkbox.js
  src/components/content-collapse/contentCollapse.js
  src/components/feedback/feedback.js
  src/components/header-center/header-center.js
  src/components/header-nav/header-nav.js
  src/components/header-slim/header-slim.js
  src/components/header/header.js
  src/components/nav-sidebar/nav-sidebar.js
  src/components/tab/tab.js
  src/components/tab/tabbutton.js
  src/templates/tmpl-base.js
  src/templates/tmpl-design-system-detail.js
  src/templates/tmpl-design-system-index.js
  src/templates/tmpl-home.js
Labels: enhancement, next

#578 feat/next-content-fix-typos
  src/pages/community.yaml
  src/pages/norme-e-riferimenti/linee-guida-di-design.yaml
  src/pages/risorse-per-progettare/progettare/architettura-dell-informazione/individua-i-contenuti.yaml
  src/pages/risorse-per-progettare/progettare/architettura-dell-informazione/organizza-i-contenuti.yaml
  src/pages/risorse-per-progettare/realizzare/costruzione-interfaccia/realizza-un-prototipo-in-alta-fedelta.yaml
Labels: content, next

#581 feat/next-content-design-standards
  src/pages/norme-e-riferimenti/linee-guida-di-design.yaml
  src/pages/norme-e-riferimenti/linee-guida-di-design/requisito-4-3.yaml
  src/pages/norme-e-riferimenti/linee-guida-di-design/requisito-4-3/azione-b.yaml
Labels: content, next

#585 Feat/iframe component view switch
  .gitignore
  gatsby-config.js
  package-lock.json
  package.json
  scripts/generate-examples.js
  src/components/component-view/component-view.js
  src/components/component-view/component-view.scss
  src/components/tab/tab.js
  src/pages/design-system/componenti/buttons.json
  src/pages/design-system/componenti/dropdown.json
  static/examples/a-tutta-larghezza-solo-su-mobile.html
  static/examples/a-tutta-larghezza.html
  static/examples/accordion-annidati.html
  static/examples/accordion.html
  static/examples/base-button.html
  static/examples/base-elementi-richiudibili.html
  static/examples/base.html
  static/examples/con-classe-.btn.html
  static/examples/con-icona-a-sinistra.html
  static/examples/con-icona.html
  static/examples/con-sfondo-header-all'hover.html
  static/examples/con-sfondo-header-attivi.html
  static/examples/dimensione-grande-large.html
  static/examples/dimensione-minima-mini.html
  static/examples/dimensione-normale-small.html
  static/examples/disabilitato.html
  static/examples/dropend-si-apre-a-destra.html
  static/examples/dropstart-si-apre-a-sinistra.html
  static/examples/dropup-si-apre-verso-l'alto.html
  static/examples/esempi-con-varianti-di-pulsanti.html
  static/examples/icona-cerchiata.html
  static/examples/menu-a-tutta-larghezza.html
  static/examples/menu-con-icona-a-destra.html
  static/examples/menu-con-icona-a-sinistra.html
  static/examples/menu-con-instestazioni-e-separatori.html
  static/examples/menu-con-intestazioni-e-separatori.html
  static/examples/menu-con-voci-grandi.html
  static/examples/menu-dark.html
  static/examples/menu-voci-attive.html
  static/examples/menu-voci-disabilitate.html
  static/examples/su-sfondo-scuro.html
  static/examples/template.html
  static/examples/usando-l'elemento-lessagreater.html
  static/examples/varianti-di-colore.html
Labels: enhancement, feature, next

#596 Changed content collapse icon
  src/components/content-collapse/contentCollapse.js
Labels: enhancement, next

#595 feat/next-content-fix
  src/pages/design-system.yaml
  src/pages/design-system/componenti.yaml
  src/pages/design-system/componenti/accordion.yaml
  src/pages/design-system/componenti/dropdown.yaml
  src/pages/design-system/fondamenti.yaml
  src/pages/modelli/comuni/adotta-il-modello-di-sito-comunale/valuta-l-adesione-al-modello-di-sito-comunale.yaml
  src/pages/progetto.yaml
  src/pages/progetto/formazione-e-disseminazione.yaml
  src/pages/progetto/visione-e-missione.yaml
  src/pages/risorse-per-progettare/comprendere/esperienza-utente/analizza-l-esperienza-d-uso.yaml
  src/pages/risorse-per-progettare/comprendere/esperienza-utente/definisci-le-personas.yaml
  src/pages/risorse-per-progettare/progettare/seo.yaml
  src/pages/risorse-per-progettare/realizzare.yaml
  src/pages/risorse-per-progettare/validare/test-di-usabilita.yaml
  src/pages/risorse-per-progettare/validare/test-di-usabilita/prepara-le-attivita-e-svolgi-i-test-di-usabilita.yaml
  src/pages/risorse-per-progettare/validare/web-analytics.yaml
Labels: content, next

#592 Fix/highlight with just icon 587
  src/components/highlight/highlight.js
Labels: bug, next

#600 feat/next-content-feedback-legal-update
  src/components/feedback/components/form-no/FormNo.js
Labels: content, next

#599 feat/next-content-work-in-progress-disclaimer
  src/pages/design-system/componenti.yaml
  src/pages/design-system/fondamenti.yaml
Labels: content, next

#598 feat/next-content-linguaggio-foundation
  src/pages/design-system/fondamenti.yaml
  src/pages/design-system/fondamenti/linguaggio.yaml
Labels: content, next

#604 feat/content-next-news-fix
  src/pages/community/notizie/20221220-ecco-l-anteprima-del-nuovo-designers-italia.yaml
Labels: content, next

#607 fix/next-content-launchnews
  src/pages/community/notizie/20221220-ecco-l-anteprima-del-nuovo-designers-italia.yaml
Labels: content, next

#605 feat/new-release-news
  _posts/2022-12-20-Ecco-l-anteprima-del-nuovo-Designers-Italia.md
Labels: content

#608 chore: add news angular bsi
  src/pages/community.yaml
  src/pages/community/eventi/20230130-angular-bootstrap-it-e-non-solo.js
  src/pages/community/eventi/20230130-angular-bootstrap-it-e-non-solo.yaml
Labels: content, next
