Repository italia/designers.italia.it, pull requests merged in 2022-03, with the labels that each got.

#278 Fix/redirect old url development kit
  _kits/it/sviluppo-interfaccia.md
Labels: bug

#288 Feat/new content for atlante page
  _projects/it/atlante-della-trasformazione-digitale.md
  assets/images/projects/atlante-della-trasformazione-digitale/README.md
Labels: content

#289 Feat/new content for atlante page
  .DS_Store
  .gitignore
  _posts/2022-01-31-atlante-trasformazione-digitale-pa.md
  _posts/2022-03-11-Community-lab-Bootstrap-italia.md
  _posts/2022-03-18-Come-UE-valuta-servizi-pubblici-digitali.md
  _projects/it/atlante-della-trasformazione-digitale.md
  assets/images/.DS_Store
  assets/images/projects/.DS_Store
  assets/images/projects/atlante-della-trasformazione-digitale/README.md
  assets/images/projects/atlante/.DS_Store
  assets/images/projects/atlante/atlante-della-trasformazione-digitale-della-pa_1.jpg
  assets/images/projects/atlante/atlante-della-trasformazione-digitale-della-pa_10.jpg
  assets/images/projects/atlante/atlante-della-trasformazione-digitale-della-pa_11.jpg
  assets/images/projects/atlante/atlante-della-trasformazione-digitale-della-pa_12.jpg
  assets/images/projects/atlante/atlante-della-trasformazione-digitale-della-pa_13.jpg
  assets/images/projects/atlante/atlante-della-trasformazione-digitale-della-pa_14.jpg
  assets/images/projects/atlante/atlante-della-trasformazione-digitale-della-pa_15.jpg
  assets/images/projects/atlante/atlante-della-trasformazione-digitale-della-pa_16.jpg
  assets/images/projects/atlante/atlante-della-trasformazione-digitale-della-pa_17.jpg
  assets/images/projects/atlante/atlante-della-trasformazione-digitale-della-pa_18.jpg
  assets/images/projects/atlante/atlante-della-trasformazione-digitale-della-pa_19.jpg
  assets/images/projects/atlante/atlante-della-trasformazione-digitale-della-pa_2.jpg
  assets/images/projects/atlante/atlante-della-trasformazione-digitale-della-pa_20.jpg
  assets/images/projects/atlante/atlante-della-trasformazione-digitale-della-pa_21.jpg
  assets/images/projects/atlante/atlante-della-trasformazione-digitale-della-pa_22.jpg
  assets/images/projects/atlante/atlante-della-trasformazione-digitale-della-pa_23.jpg
  assets/images/projects/atlante/atlante-della-trasformazione-digitale-della-pa_3.jpg
  assets/images/projects/atlante/atlante-della-trasformazione-digitale-della-pa_4.jpg
  assets/images/projects/atlante/atlante-della-trasformazione-digitale-della-pa_5.jpg
  assets/images/projects/atlante/atlante-della-trasformazione-digitale-della-pa_6.jpg
  assets/images/projects/atlante/atlante-della-trasformazione-digitale-della-pa_7.jpg
  assets/images/projects/atlante/atlante-della-trasformazione-digitale-della-pa_8.jpg
  assets/images/projects/atlante/atlante-della-trasformazione-digitale-della-pa_9.jpg
Labels: content

#293 feat/timeline/new bootstrap italia release
  _data/attivita.yml
Labels: content

#279 feat/new page atlante, ready for content
  .gitignore
  _config.yml
  _layouts/project.html
  _projects/it/atlante-della-trasformazione-digitale.md
  _sass/_designers-italia.scss
  assets/images/projects/atlante/atlante-della-trasformazione-digitale-della-pa_1.jpg
  assets/images/projects/atlante/atlante-della-trasformazione-digitale-della-pa_10.jpg
  assets/images/projects/atlante/atlante-della-trasformazione-digitale-della-pa_11.jpg
  assets/images/projects/atlante/atlante-della-trasformazione-digitale-della-pa_12.jpg
  assets/images/projects/atlante/atlante-della-trasformazione-digitale-della-pa_13.jpg
  assets/images/projects/atlante/atlante-della-trasformazione-digitale-della-pa_14.jpg
  assets/images/projects/atlante/atlante-della-trasformazione-digitale-della-pa_15.jpg
  assets/images/projects/atlante/atlante-della-trasformazione-digitale-della-pa_16.jpg
  assets/images/projects/atlante/atlante-della-trasformazione-digitale-della-pa_17.jpg
  assets/images/projects/atlante/atlante-della-trasformazione-digitale-della-pa_18.jpg
  assets/images/projects/atlante/atlante-della-trasformazione-digitale-della-pa_19.jpg
  assets/images/projects/atlante/atlante-della-trasformazione-digitale-della-pa_2.jpg
  assets/images/projects/atlante/atlante-della-trasformazione-digitale-della-pa_20.jpg
  assets/images/projects/atlante/atlante-della-trasformazione-digitale-della-pa_21.jpg
  assets/images/projects/atlante/atlante-della-trasformazione-digitale-della-pa_22.jpg
  assets/images/projects/atlante/atlante-della-trasformazione-digitale-della-pa_23.jpg
  assets/images/projects/atlante/atlante-della-trasformazione-digitale-della-pa_3.jpg
  assets/images/projects/atlante/atlante-della-trasformazione-digitale-della-pa_4.jpg
  assets/images/projects/atlante/atlante-della-trasformazione-digitale-della-pa_5.jpg
  assets/images/projects/atlante/atlante-della-trasformazione-digitale-della-pa_6.jpg
  assets/images/projects/atlante/atlante-della-trasformazione-digitale-della-pa_7.jpg
  assets/images/projects/atlante/atlante-della-trasformazione-digitale-della-pa_8.jpg
  assets/images/projects/atlante/atlante-della-trasformazione-digitale-della-pa_9.jpg
Labels: enhancement, feature, content

#297 fix/patch-minor-project-page
  _layouts/project.html
  _projects/it/atlante-della-trasformazione-digitale.md
Labels: bug

#299 fix/change cover image for the Atlante
  _projects/it/atlante-della-trasformazione-digitale.md
  assets/images/projects/atlante/atlante-della-trasformazione-digitale-della-pa_1.jpg
Labels: content
