Repository italia/designers.italia.it, pull requests merged in 2023-09, with the labels that each got.

#864 fix: graphql new notation for tags
  gatsby-node.js
Labels: enhancement

#859 content: update piano attivita
  src/data/content/community/piano-attivita.yaml
Labels: content

#872 content: "Architettura dell'informazione" and "Analisi del contesto" Open Graph images
  src/data/content/risorse-per-progettare/comprendere/analisi-del-contesto.yaml
  src/data/content/risorse-per-progettare/comprendere/analisi-del-contesto/schematizza-il-contesto-d-uso.yaml
  src/data/content/risorse-per-progettare/progettare/architettura-dell-informazione.yaml
  src/data/content/risorse-per-progettare/progettare/architettura-dell-informazione/individua-i-contenuti.yaml
  src/data/content/risorse-per-progettare/progettare/architettura-dell-informazione/organizza-i-contenuti.yaml
Labels: content

#884 feat: new issue template 💬
  .github/ISSUE_TEMPLATE/apri-una-segnalazione.it.yaml
  .github/ISSUE_TEMPLATE/config.yml
  .github/ISSUE_TEMPLATE/open-an-issue.en.yaml
Labels: feature

#895 fix: table simple-cta icons position
  src/components/simple-cta/simple-cta.scss
Labels: enhancement, design system

#900 Feat: news about the museum websites template
  src/data/content/community.yaml
  src/data/content/community/notizie/20230925-prendi-parte-anche-tu-all-evoluzione-del-design-system-del-paese.yaml
  src/data/content/community/notizie/20230927-partono-i-lavori-per-il-modello-di-sito-web-per-i-musei-civici.yaml
  src/data/content/index.yaml
  static/images/community/20230927-partono-i-lavori-per-il-modello-di-sito-web-per-i-musei-civici-1400x723.png
  static/images/community/20230927-partono-i-lavori-per-il-modello-di-sito-web-per-i-musei-civici-1920x1280.png
  static/images/community/20230927-partono-i-lavori-per-il-modello-di-sito-web-per-i-musei-civici-1920x923.png
Labels: content

#842 chore(ci): add linting to the pipeline
  .eslintrc
  .github/workflows/tests.yml
  gatsby-node.js
  package-lock.json
  package.json
  scripts/download-examples.js
  scripts/generate-examples.js
  scripts/prepare.js
  src/components/card/card.js
  src/components/checkbox/checkbox.js
  src/components/chip/chip.js
  src/components/component-view/component-view.js
  src/components/content-collapse/contentCollapse.js
  src/components/content-select/components/content-select-item/content-select-item.js
  src/components/content-select/content-select.js
  src/components/dropdown/dropdown.js
  src/components/feedback/feedback.js
  src/components/footer-main/footer-main.js
  src/components/header-center/header-center.js
  src/components/header-menu-link/header-menu-link.js
  src/components/header-pre/header-pre.js
  src/components/header-slim/header-slim.js
  src/components/header/header.js
  src/components/hero/hero.js
  src/components/highlight-cards/highlight-cards.js
  src/components/image-icons/image-icons.js
  src/components/image-responsive/image-responsive.js
  src/components/interest-aside/interest-aside.js
  src/components/kangaroo/kangaroo.js
  src/components/label-textarea/label-text-area.js
  src/components/labelinput/labelinput.js
  src/components/last-update/last-update.js
  src/components/list-archive-events/list-archive-events.js
  src/components/list-archive-news/list-archive-news.js
  src/components/list-item/list-item.js
  src/components/list/list.js
  src/components/nav-other-links/nav-other-links.js
  src/components/nav-other-prev-next/nav-other-prev-next.js
  src/components/nav-position/nav-position.js
  src/components/nav-sidebar/nav-sidebar.js
  src/components/search-main/search-main.js
  src/components/section-editorial/section-editorial.js
  src/components/seo/seo-get-site-metadata.js
  src/components/seo/seo.js
  src/components/share-button/share-button.js
  src/components/simple-cta/simple-cta.js
  src/components/subscribe/subscribe.js
  src/components/tab/tab.js
  src/components/tab/tabbutton.js
  src/components/tag/tag.js
  src/components/tooltip/tooltip.js
  src/components/topics/topics.js
  src/templates/design-system-component.js
  src/templates/design-system-index-components-tags.js
  src/templates/design-system-index.js
  src/templates/tag.js
Labels: feature

#906 feat: enable markdown on tables
  src/components/table/table.js
Labels: feature, design system

#908 feat: enhance tables
  src/components/component-view/component-view.js
  src/components/table/table.js
  src/components/table/table.scss
  src/data/content/design-system/fondamenti/technical-template.yaml
  src/pages/{content.relativePath}.js
Labels: enhancement, feature, design system
