Repository italia/designers.italia.it, pull requests merged in 2023-01, with the labels that each got.

#612 fix/Next-remove-chapter-and-paragraph-numbering
  src/pages/norme-e-riferimenti/linee-guida-di-design/requisito-4-3/azione-2.yaml
Labels: content, next

#602 feat/privacy-policy-update
  _pages/it/privacy-policy.md
Labels: enhancement, content, next

#616 feat/next-enable-matomo
  gatsby-config.js
Labels: feature, next

#617 feat/enable-matomo
  _config.yml
  _includes/head.html
  _includes/matomo.html
Labels: feature
