Repository italia/designers.italia.it, pull requests merged in 2023-02, with the labels that each got.

#635 feat: implement client side redirects
  gatsby-config.js
  gatsby-node.js
  package-lock.json
  package.json
  src/data/content/community/piano-attivita.yaml
Labels: feature, next

#640 feat: new website preview banner
  _includes/header.html
Labels: content

#644 fix: link to the content files in the source repo
  src/components/last-update/last-update.js
Labels: bug, next

#647 feat: add client side search engine
  gatsby-config.js
  package-lock.json
  package.json
  src/components/search-main/search-main.js
  src/components/search-main/search-main.scss
  src/data/content/index.yaml
  src/pages/{content.relativePath}.js
Labels: feature, next

#654 feat: 404 blank page
  src/pages/404.js
Labels: feature, next

#651 Fixed the z-index of the "backToTop" button and the copy notification on mobile
  bootstrap-italia/src/scss/custom/_back-to-top.scss
  bootstrap-italia/src/scss/custom/_notifications.scss
  src/components/nav-sidebar/nav-sidebar.js
  src/templates/design-system-component.js
Labels: bug, next
