Repository italia/designers.italia.it, pull requests merged in 2023-08, with the labels that each got.

#845 Feat: News "I libri per l’estate consigliati da Designers Italia"
  src/data/content/community.yaml
  src/data/content/community/notizie/20230802-i-libri-per-l-estate-consigliati-da-designers-italia.yaml
  src/data/content/index.yaml
  static/images/community/20230802-i-libri-per-l-estate-consigliati-da-designers-italia-1400x723.png
  static/images/community/20230802-i-libri-per-l-estate-consigliati-da-designers-italia-1920x1280.png
  static/images/community/20230802-i-libri-per-l-estate-consigliati-da-designers-italia-1920x923.png
Labels: content

#852 Feat: "Quadro Sinottico" in open format
  static/files/resources/template_quadro_sinottico_open.ods
Labels: content

#853 fix: serve html examples from static in dev mode
  gatsby-node.js
Labels: bug, design system

#855 chore: update BSI dependency to 2.6.1
  package-lock.json
  package.json
Labels: dependencies

#860 content: add button shortlink for managers
  src/data/content/design-system.yaml
Labels: content
