Repository italia/designers.italia.it, pull requests merged in 2024-12, with the labels that each got.

#1483 content: update Dichiarazione accessibilita
  src/data/footer.yaml
Labels: content, a11y

#1486 fix: url typos
  src/data/content/modelli/contribuisci-ai-modelli/come-contribuire-ai-modelli.yaml
Labels: bug

#1487 fix: update hero media
  static/images/design-system/componenti/hero-anatomy.jpg
  static/images/design-system/componenti/hero-specs.png
Labels: content, design system

#1493 fix: a11y improvements
  src/components/search-main/search-main.js
  src/components/section/section.js
  src/components/subscribe/subscribe.js
Labels: a11y

#1495 fix(a11y): more improvements
  src/components/list-archive-ds-tags/list-archive-ds-tags.js
  src/components/list-archive-events/list-archive-events.js
  src/components/list-archive-media/list-archive-media.js
  src/components/list-archive-news/list-archive-news.js
  src/components/search-main/search-main.js
  src/data/content/index.yaml
  src/pages/{content.relativePath}.js
Labels: a11y
